#!/bin/bash

# Default values
SEARCH_DIR=$(pwd)
START_DATE="2024-01-01"
END_DATE=""
AUTHOR=""

# Parse named parameters
while getopts d:s:e:a: flag
do
    case "${flag}" in
        d) SEARCH_DIR=${OPTARG};;
        s) START_DATE=${OPTARG};;
        e) END_DATE=${OPTARG};;
        a) AUTHOR=${OPTARG};;
    esac
done

total_add=0

# Optional end date argument for git log
END_DATE_ARG=""
if [ -n "$END_DATE" ]; then
    END_DATE_ARG="--before=$END_DATE"
fi

while IFS= read -r repo; do 
    echo "Repository: ${repo}"
    
    add=$(cd "${repo}/.." && git log --author="$AUTHOR" --since="$START_DATE" $END_DATE_ARG --pretty=tformat: --numstat | awk '{ add += $1 } END { print add }')

    total_add=$((total_add + add))
    
    echo "Added lines in this repo by $AUTHOR: $add"
    echo
done < <(find "$SEARCH_DIR" -type d -name .git) 

echo "Total added lines across all repositories by $AUTHOR from $START_DATE to ${END_DATE:-now}: $total_add"
